config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  root 'welcome#index'

  resources :users, only: [:show] do
    resources :items, only: [:create, :new, :destroy]
  end

end

app/models/item.rb
class Item < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  belongs_to :user

  def time_remaining
    ((self.created_at.end_of_day.advance(days: 7)) - Time.zone.now).to_i/86400
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  validates_presence_of :username
  validates_uniqueness_of :username, :email

  def confirm!
    super
    welcome_message
  end

  def email_required?
    false
  end


  private

  def welcome_message
    UserMailer.welcome_message(self).deliver
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, :except => [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:username, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password) }
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_user
  before_action :only_permit_current_user, only: [:new, :create, :destroy]

  def new
    @item = Item.new
  end

  def create
    @item = @user.items.build(item_params)
    @item.user = @user

    if @item.save
      flash[:notice] = "Item was saved."
    else
      flash[:error] = "There was an error saving the item.  Please try again."
    end

    respond_to do |format|
      format.html do
        redirect_to user_path(@user)
      end
      format.js
    end
  end

  def destroy
    @item = @user.items.find(params[:id])

    if @item.destroy
      flash.now[:notice] = "Item was removed from your list - Congratulations!"

    else
      flash[:alert] = "Item could not be removed from your list.  Try again."
    end

    respond_to do |format|
      format.html do
        redirect_to root_url
      end
      format.js
    end
  end

  private

  def item_params
    params.require(:item).permit(:description)
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def only_permit_current_user
    unless user_signed_in? && current_user == @user

      respond_to do |format|
        format.html do
          flash[:alert] = "You must be logged in as that user to add or delete items."
          redirect_to user_path(@user), status: 303
        end
        format.js do
          render 'only_permit_current_user.js.erb'
        end
      end
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def create
    super
    if create_session?
      user.save!
      redirect_to @user
    end
  end

  def destroy
    super
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :only_permit_current_user

  def show
      @user = User.find(params[:id])
      @items = @user.items
  end

  private

  def only_permit_current_user
    @user = User.find(params[:id])
    unless user_signed_in? && current_user == @user

      respond_to do |format|
        format.html do
          flash[:alert] = "You must be logged in as that user to perform that action."
          redirect_to root_path, status: 303
        end
        format.js do
          render 'only_permit_current_user.js.erb'
        end
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item] do |f| %>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control', autofocus: true, placeholder: "Enter the task", required: true %>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <%= link_to "Back", user_path(@user), class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<%= link_to "", [user, item], method: :delete, remote: true, class: 'glyphicon glyphicon-thumbs-up', data: { confirm: "Are you sure?" }%>

<!-- '/users/2/items/6'
user_item_path(user, item)
[user, item] -->

app/views/items/create.js.erb
<% if @item.saved? %>
  $('.alert').hide();
  $('.flash').prepend("<div class='alert alert-success alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= flash[:notice] %></div>");
<% else %>
  $('.alert').hide();
  $('.flash').prepend("<div class='alert alert-warning alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><% flash[:error] %></div>");
<% end %>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
  $('.alert').hide();
  $('#item-<%= @item.id %>').hide();
  $('.flash').prepend("<div class='alert alert-success alert-dismissible fade-in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= flash[:notice] %></div>");
<% else %>
  $('.alert').hide();
  $('.flash').prepend("<div class='alert alert-danger alert-dismissible fade-in' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button><%= flash[:alert] %></div>");
<% end %>

app/views/items/new.html.erb
<h1>New Item</h1>
<p>Enter a task below - remember to define the task such that it can be completed within 7 days.  Split up larger tasks if need be.</p>
<%= render partial: 'form', locals: { user: @user, item: @item } %>

app/views/items/only_permit_current_user.js.erb
$('.alert').hide();
$('.flash').prepend("<div class='alert alert-danger alert-dismissible' role='alert'><button type='button' class='close' data-dismiss='alert' aria-label='Close'><span aria-hidden='true'>&times;</span></button>You must be logged in as that user to perform that action.</div>");

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Blocitoff", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
         <p class="text-muted">Logged in as: <strong><%= current_user.email %></strong></p>
         <li><%= link_to "My List", user_path(current_user), :class => 'navbar-link' %></li>
         <li><%= link_to "Edit profile", edit_user_registration_path, :class => 'navbar-link' %></li>
         <li><%= link_to "Log out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
       <% else %>
         <li><%= link_to "Home", root_path, :class => 'navbar-link'  %></li>
         <li><%= link_to "Log in", new_user_session_path, :class => 'navbar-link'  %></li>
       <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/superhero/bootstrap.min.css" rel="stylesheet" integrity="sha256-AbCXzDgd7Vj/2JrsXgjrLdYZ92AgN262cXvQr4tAQa4= sha512-cA2CLCEXBR7hnXGgSNa+TaQ7WT2zW1IVm6uCLcu3ebHNhy+VIudw9kwgHlcL57wCiiXLZ1x7yT5Mv3QkDO2XZA==" crossorigin="anonymous"> -->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="flash">
        <% if flash[:notice] %>
          <div class="alert alert-success alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= flash[:notice] %></div>
        <% elsif flash.now[:alert] %>
          <div class="alert alert-danger alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= flash.now[:alert] %></div>
        <% elsif flash[:alert] %>
          <div class="alert alert-warning alert-dismissible" role="alert"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button><%= flash[:alert] %></div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h1>Hello <%= @user.username %> --- <small>Ready to be productive?</small></h1>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h2>Tasks At-hand</h2>
      <table class="table table-bordered">
        <thead>
          <tr>
            <td><strong>Description</strong></td>
            <td><strong>Time Remaining</strong></td>
            <td><strong>Completed?</strong></td>
          </tr>
        </thead>
        <tbody>
          <% @user.items.each do |item| %>
            <tr id="item-<%= item.id %>">
              <td><%= item.description %></td>
              <td>
                <%= pluralize(item.time_remaining, 'day') %>
              </td>
              <td>
                <%= render partial: 'items/item', locals: { user: @user, item: item } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <% if user_signed_in? && @user == current_user %>
          <%= link_to "New Item", new_user_item_path(@user), class: 'btn btn-success' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="center jumbotron">
  <h1>Blocitoff</h1>
  <h3>
    A self-destructing to-do list to keep you focused on the things that really matter.
  </h3>
  <%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-lg btn-primary" %>
</div>